import { FilterOptions } from "@/types/filters";

export const filterOptions: FilterOptions = {
  availableTechStacks: [
    // 알파벳 순으로 정렬된 모든 기술 스택
    "Adobe XD",
    "Alpine.js",
    "Amplitude",
    "Android",
    "Angular",
    "Ansible",
    "Ant Design",
    "Apache",
    "Apollo",
    "ASP.NET",
    "Astro",
    "AWS",
    "Azure",
    "Babel",
    "Babylon.js",
    "Bitbucket",
    "Bootstrap",
    "Bulma",
    "C",
    "C#",
    "C++",
    "Cassandra",
    "Chai",
    "Chakra UI",
    "Chef",
    "CircleCI",
    "Cloudflare",
    "Contentful",
    "Cordova",
    "CouchDB",
    "CSS",
    "Cypress",
    "Dart",
    "Datadog",
    "DigitalOcean",
    "Discord",
    "Django",
    "Docker",
    "Drupal",
    "DynamoDB",
    "Echo",
    "Electron",
    "Elixir",
    "Emotion",
    "ESLint",
    "Ethers.js",
    "Express",
    "FastAPI",
    "Fastify",
    "Fiber",
    "Figma",
    "Firebase",
    "Flask",
    "Flutter",
    "Framer",
    "GameMaker",
    "Gatsby",
    "GCP",
    "Gin",
    "Git",
    "GitHub",
    "GitHub Actions",
    "GitLab",
    "GitLab CI",
    "Go",
    "Godot",
    "Google Analytics",
    "GraphQL",
    "gRPC",
    "GTK",
    "Hardhat",
    "Heroku",
    "HTML",
    "Hugging Face",
    "Illustrator",
    "IndexedDB",
    "InfluxDB",
    "InVision",
    "Ionic",
    "IPFS",
    "Java",
    "Java Android",
    "JavaScript",
    "JavaFX",
    "Jenkins",
    "Jest",
    "Jira",
    "Jotai",
    "Jupyter",
    "Keras",
    "Koa",
    "Kotlin",
    "Kubernetes",
    "LangChain",
    "Laravel",
    "Less",
    "Linear",
    "Lit",
    "LocalStorage",
    "LogRocket",
    "Magento",
    "MariaDB",
    "Material-UI",
    "Matplotlib",
    "MetaMask",
    "Mixpanel",
    "MobX",
    "Mocha",
    "MongoDB",
    "MySQL",
    "Neo4j",
    "NestJS",
    "Netlify",
    "New Relic",
    "Next.js",
    "Nginx",
    "Node.js",
    "Notion",
    "NumPy",
    "Nuxt.js",
    "OpenAI",
    "OpenCV",
    "Oracle",
    "Pandas",
    "Parcel",
    "Phaser",
    "PHP",
    "Photoshop",
    "Pinia",
    "Playwright",
    "PostCSS",
    "PostgreSQL",
    "Preact",
    "Prettier",
    "Principle",
    "Puppeteer",
    "PWA",
    "PyTorch",
    "Qt",
    "React",
    "React Native",
    "Recoil",
    "Redis",
    "Redux",
    "Relay",
    "Remix",
    "REST API",
    "Rollup",
    "Ruby",
    "Ruby on Rails",
    "Rust",
    "Sanity",
    "Sass",
    "Scala",
    "Scikit-learn",
    "Selenium",
    "Sentry",
    "Service Workers",
    "Shopify",
    "Sketch",
    "Slack",
    "Socket.io",
    "Solid.js",
    "Solidity",
    "Spring",
    "Spring Boot",
    "SQL Server",
    "SQLite",
    "Stencil",
    "Storybook",
    "Strapi",
    "Styled Components",
    "Stylus",
    "Supabase",
    "Svelte",
    "SvelteKit",
    "Swift",
    "SwiftUI",
    "Symfony",
    "Tailwind",
    "Tauri",
    "TensorFlow",
    "Terraform",
    "Testing Library",
    "Three.js",
    "Tkinter",
    "Trello",
    "tRPC",
    "Truffle",
    "TypeScript",
    "Unity",
    "Unreal Engine",
    "Vagrant",
    "Valtio",
    "Vercel",
    "Vite",
    "Vitest",
    "Vue",
    "Vuex",
    "Web3.js",
    "WebAssembly",
    "Webpack",
    "WebRTC",
    "WooCommerce",
    "WordPress",
    "WPF",
    "Xamarin",
    "Zeplin",
    "Zustand",
  ],

  statusOptions: [
    { value: "all", label: "전체" },
    { value: "recruiting", label: "모집중" },
    { value: "urgent", label: "마감임박" },
    { value: "completed", label: "모집완료" },
  ],

  dateOptions: [
    { value: "all", label: "전체 기간" },
    { value: "thisWeek", label: "이번 주" },
    { value: "thisMonth", label: "이번 달" },
    { value: "urgent", label: "마감 임박 (7일 이내)" },
  ],

  sortOptions: [
    { value: "latest", label: "최신순" },
    { value: "deadline", label: "마감일순" },
    { value: "members", label: "모집인원순" },
    { value: "popular", label: "인기순" },
  ],
};
